"""add_ab_outreach_options

Revision ID: d6b5344235ae
Revises: 003_add_dnd_registry
Create Date: 2026-06-07 18:10:32.580038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6b5344235ae'
down_revision: Union[str, None] = '003_add_dnd_registry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_execution_logs', 'session_id',
               existing_type=sa.UUID(),
               comment='Links all agent executions within a single RM request',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'input_masked',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Agent input with all PII replaced by Presidio tokens — safe to store',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_profiles', 'product_holdings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_profiles', 'behavioral_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'external_cbs_id',
               existing_type=sa.VARCHAR(length=512),
               comment='Fernet-encrypted CBS account ID',
               existing_nullable=True)
    op.alter_column('customers', 'risk_tier',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='risktier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'kyc_status',
               existing_type=postgresql.ENUM('complete', 'pending', 'expired', name='kycstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'relationship_tenure_months',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('detected_events', 'confidence_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='0.000 to 1.000',
               existing_nullable=False)
    op.alter_column('detected_events', 'signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Evidence payload: which rules fired with supporting transaction IDs',
               existing_nullable=False)
    op.alter_column('detected_events', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Events become stale after this date — opportunity window has passed',
               existing_nullable=True)
    op.alter_column('detected_events', 'actioned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True once an opportunity has been created from this event',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Collection: product_catalog | policy_docs | persona_playbooks | market_context',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'source_file',
               existing_type=sa.VARCHAR(length=255),
               comment='Relative path from knowledge_base/ e.g. product_catalog/personal_loan_eligibility.md',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='Position of this chunk within the source document (0-indexed)',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA256 of chunk_text — used for idempotent upsert',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment='1536-dim vector (Matryoshka truncation of text-embedding-3-large)',
               existing_comment='1536-dim Matryoshka-truncated text-embedding-3-large vector stored as ARRAY(Float). \n         Cast to vector(1536) for cosine similarity queries. \n         Migrate to native vector type for HNSW index support.',
               existing_nullable=True)
    op.alter_column('knowledge_embeddings', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Document version from file metadata',
               existing_nullable=True)
    op.alter_column('knowledge_embeddings', 'effective_date',
               existing_type=sa.VARCHAR(length=20),
               comment='Effective date from document front matter',
               existing_nullable=True)
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_trgm'), table_name='knowledge_embeddings', postgresql_ops={'chunk_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('opportunities', 'event_id',
               existing_type=sa.UUID(),
               comment='The life event that triggered this opportunity — nullable for proactive scoring',
               existing_nullable=True)
    op.alter_column('opportunities', 'priority_score',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('opportunities', 'conversion_prob',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=None,
               comment='0.000 to 1.000 from XGBoost model',
               existing_nullable=False)
    op.alter_column('opportunities', 'revenue_potential',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Estimated bank revenue from this product over 12 months',
               existing_nullable=True)
    op.alter_column('opportunities', 'risk_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('opportunities', 'explanation',
               existing_type=sa.TEXT(),
               comment='RM-readable reasoning card generated by ExplainabilityAgent (gpt-4o)',
               existing_nullable=True)
    op.alter_column('opportunities', 'status',
               existing_type=postgresql.ENUM('new', 'rm_viewed', 'outreach_sent', 'converted', 'dismissed', name='opportunitystatus'),
               server_default=None,
               existing_nullable=False)
    op.add_column('outreach_campaigns', sa.Column('message_option_a', sa.Text(), nullable=True))
    op.add_column('outreach_campaigns', sa.Column('message_option_b', sa.Text(), nullable=True))
    op.alter_column('outreach_campaigns', 'provider_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Message ID from WhatsApp/Twilio/SendGrid for delivery receipt correlation',
               existing_nullable=True)
    op.alter_column('relationship_managers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_rm_email'), table_name='relationship_managers')
    op.drop_constraint(op.f('uq_rm_email'), 'relationship_managers', type_='unique')
    op.create_index(op.f('ix_relationship_managers_email'), 'relationship_managers', ['email'], unique=True)
    op.alter_column('transactions', 'merchant_category',
               existing_type=sa.VARCHAR(length=10),
               comment="ISO 18245 MCC code e.g. '5094' for jewellery",
               existing_nullable=True)
    op.alter_column('transactions', 'merchant_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Merchant display name — not PII',
               existing_nullable=True)
    op.alter_column('transactions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='Optional notes for testing and audit (not a customer-facing field)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Optional notes for testing and audit (not a customer-facing field)',
               existing_nullable=True)
    op.alter_column('transactions', 'merchant_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Merchant display name — not PII',
               existing_nullable=True)
    op.alter_column('transactions', 'merchant_category',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="ISO 18245 MCC code e.g. '5094' for jewellery",
               existing_nullable=True)
    op.drop_index(op.f('ix_relationship_managers_email'), table_name='relationship_managers')
    op.create_unique_constraint(op.f('uq_rm_email'), 'relationship_managers', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rm_email'), 'relationship_managers', ['email'], unique=True)
    op.alter_column('relationship_managers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('outreach_campaigns', 'provider_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Message ID from WhatsApp/Twilio/SendGrid for delivery receipt correlation',
               existing_nullable=True)
    op.drop_column('outreach_campaigns', 'message_option_b')
    op.drop_column('outreach_campaigns', 'message_option_a')
    op.alter_column('opportunities', 'status',
               existing_type=postgresql.ENUM('new', 'rm_viewed', 'outreach_sent', 'converted', 'dismissed', name='opportunitystatus'),
               server_default=sa.text("'new'::opportunitystatus"),
               existing_nullable=False)
    op.alter_column('opportunities', 'explanation',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='RM-readable reasoning card generated by ExplainabilityAgent (gpt-4o)',
               existing_nullable=True)
    op.alter_column('opportunities', 'risk_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('opportunities', 'revenue_potential',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Estimated bank revenue from this product over 12 months',
               existing_nullable=True)
    op.alter_column('opportunities', 'conversion_prob',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=sa.text('0.000'),
               comment=None,
               existing_comment='0.000 to 1.000 from XGBoost model',
               existing_nullable=False)
    op.alter_column('opportunities', 'priority_score',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('opportunities', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The life event that triggered this opportunity — nullable for proactive scoring',
               existing_nullable=True)
    op.create_index(op.f('ix_knowledge_embeddings_chunk_trgm'), 'knowledge_embeddings', ['chunk_text'], unique=False, postgresql_ops={'chunk_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('knowledge_embeddings', 'effective_date',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Effective date from document front matter',
               existing_nullable=True)
    op.alter_column('knowledge_embeddings', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Document version from file metadata',
               existing_nullable=True)
    op.alter_column('knowledge_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment='1536-dim Matryoshka-truncated text-embedding-3-large vector stored as ARRAY(Float). \n         Cast to vector(1536) for cosine similarity queries. \n         Migrate to native vector type for HNSW index support.',
               existing_comment='1536-dim vector (Matryoshka truncation of text-embedding-3-large)',
               existing_nullable=True)
    op.alter_column('knowledge_embeddings', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA256 of chunk_text — used for idempotent upsert',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Position of this chunk within the source document (0-indexed)',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'source_file',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Relative path from knowledge_base/ e.g. product_catalog/personal_loan_eligibility.md',
               existing_nullable=False)
    op.alter_column('knowledge_embeddings', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Collection: product_catalog | policy_docs | persona_playbooks | market_context',
               existing_nullable=False)
    op.alter_column('detected_events', 'actioned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='True once an opportunity has been created from this event',
               existing_nullable=False)
    op.alter_column('detected_events', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Events become stale after this date — opportunity window has passed',
               existing_nullable=True)
    op.alter_column('detected_events', 'signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment=None,
               existing_comment='Evidence payload: which rules fired with supporting transaction IDs',
               existing_nullable=False)
    op.alter_column('detected_events', 'confidence_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='0.000 to 1.000',
               existing_nullable=False)
    op.alter_column('customers', 'relationship_tenure_months',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('customers', 'kyc_status',
               existing_type=postgresql.ENUM('complete', 'pending', 'expired', name='kycstatus'),
               server_default=sa.text("'pending'::kycstatus"),
               existing_nullable=False)
    op.alter_column('customers', 'risk_tier',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='risktier'),
               server_default=sa.text("'low'::risktier"),
               existing_nullable=False)
    op.alter_column('customers', 'external_cbs_id',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Fernet-encrypted CBS account ID',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'behavioral_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('customer_profiles', 'product_holdings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'input_masked',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment=None,
               existing_comment='Agent input with all PII replaced by Presidio tokens — safe to store',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Links all agent executions within a single RM request',
               existing_nullable=False)
    # ### end Alembic commands ###
